cs361fall2017/team23

src/main/java/models/Game.java

In this branch, I implemented the remove function so a card can be removed from a column if the Aces Up rules allow it to be.
Referencing Issue: #

Remove functionality

---

src/main/java/models/Game.java

I pulled the most recent version of the master which had Susmita's work on it, branched it, added my code, now merging with master

Add shuffle functionality and game constructor

---

src/main/java/models/Game.java

Function for checking if a column has an cards in it

Added columnHasCards function

---

src/main/java/models/Game.java

This feature deals four cards when the deal button is clicked

Added dealFour functionality

---

src/main/java/models/Game.java

Reverts cs361fall2017/team23#13

Revert "Added dealFour functionality"

---

src/main/java/models/Game.java

Accidentally accepted Tasnia's revert dealFour pull request. Someone accept this pull request so the dealFour functionality is actually present in our code.

Revert "Revert "Added dealFour functionality""

---

src/main/java/models/Game.java

I overrode our previous code with the given code for this assignment, if you click the "view" button on the right you can see all the code

I put the given code for Sprint 2 in here

---

src/main/java/assets/css/custom.css

Background change

---

src/main/java/models/Game.java
src/main/java/views/AcesUp/AcesUp.flt.html

In some situations I am getting a 500 server response error with the remove function. In these situations, the error does not pop up as there is no data being returned saying that the error should pop up.

Implementing error popup

---

src/main/java/models/Game.java

I've gotta blank space babyyy, and I'll put an Ace
Addresses Issue #39!

Only Aces can go on blank spaces

---

src/main/java/models/Game.java
src/main/java/views/AcesUp/AcesUp.flt.html

Now says only Aces can move to blank spaces

Alter the rules in the HTML

---

src/main/java/controllers/ApplicationController.java
src/main/java/models/Deck.java
src/main/java/models/Game.java

Game no longer "creates or manages" deck. Aces Up is still fully functional and Deck class is fully integrated

Game uses deck

---

src/main/java/models/Columns.java
src/main/java/models/Deck.java
src/main/java/models/Game.java
src/main/java/views/AcesUp/AcesUp.flt.html

Columns class completely integrated into Aces Up. Game is fully functional with new class added and is ready for sprint 4 now. Also removed commented out code that we no longer need.

Columns Refactoring Done

---

src/main/java/models/SpanishCard.java
src/main/java/models/SpanishDeck.java
src/main/java/models/SpanishGame.java
src/main/java/models/SpanishSuit.java

I didn't update the html symbols
Does SpanishCard intializer for the suit need to be changed?

Added suit, deck, and card class for the Spanish deck

---

src/main/java/controllers/ApplicationController.java
src/main/java/models/SpanishCard.java
src/main/java/models/SpanishDeck.java
src/main/java/models/SpanishGame.java
src/main/java/models/SpanishSuit.java
src/main/java/views/AcesUp/AcesUp.flt.html

Front End is now working. However, it is not integrated with the SpanishGame class - I commented out all those spanish classes to make my point. I tried to get it to work with the spanish classes including making changes in the application controller but I couldn't get it to work. I also think that we are overthinking it. My thoughts are that we don't need separate spanish game class but we just need to work with in the given game classes and use OO principles implement spanish game rules. We definitely need to discuss this further.

Spanishchoice

---

src/main/java/conf/Routes.java
src/main/java/controllers/ApplicationController.java
src/main/java/models/Game.java
src/main/java/models/SpanishCard.java
src/main/java/models/SpanishDeck.java
src/main/java/models/Suit.java
src/main/java/views/AcesUp/AcesUp.flt.html

Reverts cs361fall2017/team23#53

Revert "Revert "Spanishchoice""

---

src/main/java/models/Game.java

What was supposed to go up with Susmita's pull request but for some reason didn't (#54)

Damage Control

---

src/main/java/models/Game.java

Adding Spanish deal four into game.java

Fix Spanish deal four

---

src/main/java/models/Game.java

Implemented remove function with new rule for comodines for the Spanish deck.

New removeSpanish function

---

src/main/java/models/Game.java

Fixed up spanishRemove and refactored to get rid of long method

Wierdremoveglitch

---

src/main/java/controllers/ApplicationController.java
src/main/java/models/Game.java
src/main/java/models/SpanishCard.java
src/test/java/controllers/ApiControllerDocTesterTest.java
src/test/java/models/testCard.java
src/test/java/models/testGame.java

I added some new testing functions for Spanish Deck. However, some of the tests that were already given to us are failing. So testRemove and testCustomDeal are failing because we have our code setup in such a way that the deck constructor automatically shuffles the deck rendering calling g.customDeal() ineffective. The other test that is failing is testMoveCard and that is failing because the test they have given us doesn't take into account that we can only move an Ace card (Sprint 3 rule). These are the issues I will be discussing with the TA. Otherwise all the other tests are working and we only have a few more unit tests to write.

Test integration

---

src/test/java/models/testGame.java

Test spanish remove function in game.java

---

src/test/java/models/testCard.java

Test Spanish move card unit test for extra credit! someone please look over and merge :)

Unit testing extra credit

---

src/main/java/conf/Routes.java
src/main/java/controllers/ApplicationController.java
src/main/java/models/Game.java
src/main/java/views/AcesUp/AcesUp.flt.html
src/test/java/models/testGame.java

Changed app controller and routes to work with one dealfour function and minor fix in remove

AppController fix for refactored code

---

src/main/java/views/AcesUp/AcesUp.flt.html

rule update
